const layer=document.createElement('div');layer.className='floating-pets';layer.setAttribute('aria-label','Brain Cat companion');document.body.append(layer);
let resting=false,currentTab='cat';
const reduce=()=>document.body.classList.contains('reduced')||matchMedia('(prefers-reduced-motion: reduce)').matches;
function cat(i){const shapes=[
'M25 64 Q12 48 26 28 L22 12 40 23 Q54 18 65 26 L81 14 78 37 Q87 53 70 65 L65 85 35 85Z',
'M22 73 Q9 51 29 39 L33 19 45 34 Q58 29 68 38 L83 23 78 49 Q85 62 66 74 L58 87 28 87Z',
'M18 75 Q20 52 40 49 L43 28 54 40 68 25 68 47 Q87 57 79 76 Q53 94 18 75Z'];return `<svg viewBox="0 0 110 110" aria-hidden="true"><g class="neural-pet-body"><path class="pet-outline" d="${shapes[i]}"/><path class="pet-tail" d="M68 80 Q103 81 94 54 Q91 43 87 52"/><path class="pet-network" d="M27 48 47 58 65 42 65 76 40 76 27 48 M47 58 40 76 M47 58 65 76"/><g class="pet-eyes"><ellipse cx="40" cy="44" rx="3" ry="4"/><ellipse cx="63" cy="44" rx="3" ry="4"/></g><path class="pet-mouth" d="m48 54 4 4 4-4"/><circle class="pet-neuron" cx="47" cy="58" r="2"/><circle class="pet-neuron" cx="65" cy="76" r="2"/></g></svg>`;}

const cast=[['Mochi','British shorthair','belly','Follow the evidence.'],['Pip','Siamese','shy','You found me. Or did you?'],['Nori','Maine coon','nudge','Just straightening your desk.']];
const pets=cast.map(([name,breed,action,line],i)=>{const b=document.createElement('button');b.type='button';b.className='roaming-cat '+action;b.setAttribute('aria-label',`${name}, ${breed} companion. ${line}`);b.innerHTML=cat(i)+`<span class="pet-whisper">${line}</span>`;layer.append(b);let timer;const play=()=>{if(resting||reduce())return;clearTimeout(timer);b.classList.add('playing');if(action==='shy'){const x=parseFloat(b.style.left)||0;b.style.left=Math.max(8,Math.min(innerWidth-90,x+(x>innerWidth/2?-65:65)))+'px';}if(action==='nudge'){const p=document.querySelector('.terminal-box,.panel');if(p){p.animate([{transform:'translateX(0)'},{transform:'translateX(3px)'},{transform:'translateX(-1px)'},{transform:'translateX(0)'}],{duration:650,easing:'ease-in-out'});}}timer=setTimeout(()=>b.classList.remove('playing'),1800);};b.addEventListener('pointerenter',play);b.addEventListener('click',play);b.addEventListener('focus',()=>b.classList.add('focused'));b.addEventListener('blur',()=>b.classList.remove('focused'));return b;});
function place(){pets.forEach((b,i)=>{b.style.left=Math.max(8,Math.min(innerWidth-85,innerWidth*[.24,.61,.9][i]))+'px';b.style.bottom=(i===1?70:10)+'px';});}
place();window.addEventListener('resize',place);
window.addEventListener('sheriff-pets',e=>{resting=e.detail.locked;if(currentTab!==e.detail.tab){currentTab=e.detail.tab;place();}layer.classList.toggle('resting',resting);layer.classList.toggle('home-pets',currentTab==='cat');});
setInterval(()=>{if(document.hidden||resting||reduce())return;pets.forEach((b,i)=>{if(b.matches(':hover,:focus'))return;const x=parseFloat(b.style.left)||0;const next=Math.max(8,Math.min(innerWidth-85,x+(Math.random()-.5)*90));b.style.left=next+'px';b.classList.add('strolling');setTimeout(()=>b.classList.remove('strolling'),2200);});},8500);
