import {initLab,initAtlas,initRadar} from './research-desks.js';
import model from './cortex-data.mjs';
const $=s=>document.querySelector(s),text=(s,v)=>$(s).textContent=v;
let session=location.hash.slice(1)||sessionStorage.getItem('braincat-session')||'',configured=false,busy=false,selectedMode='live',paused=matchMedia('(prefers-reduced-motion: reduce)').matches,phase=0,frame=0,result=null;
if(location.hash){sessionStorage.setItem('braincat-session',session);history.replaceState(null,'',location.pathname);}
async function action(body){const r=await fetch('/api/action',{method:'POST',headers:{'Content-Type':'application/json','x-sheriff-session':session},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw Error(d.error||'Request failed');return d;}
$('#settings').onclick=()=>$('#connection').showModal();$('#cancel').onclick=()=>$('#connection').close();
$('#key-form').onsubmit=async e=>{e.preventDefault();try{await action({type:'research-key',key:$('#api-key').value});$('#api-key').value='';configured=true;selectedMode='live';text('#source','BITQUERY / LIVE HISTORY REQUESTS');text('#connected','●');text('#key-status','Saved in memory. Access will be checked on your first request.');$('#connection').close();}catch(e){text('#key-status',e.message);}};
$('#disconnect').onclick=async()=>{try{await action({type:'research-disconnect'});configured=false;text('#source','SAVED HISTORY / NO LIVE KEY');text('#connected','○');text('#key-status','Disconnected.');}catch(e){text('#key-status',e.message);}};
const examples=[model.examples[0],model.examples[30],model.examples[60]];
document.querySelectorAll('.example').forEach((b,i)=>{b.textContent=(examples[i].symbol||`Sample ${i+1}`)+' ↗';b.onclick=()=>{$('#contract').value=examples[i].token;selectedMode='archive';$('#search').requestSubmit();};});
$('#contract').addEventListener('input',()=>selectedMode='live');
const delay=ms=>new Promise(r=>setTimeout(r,ms));
function setPhase(n,label){phase=n;text('#phase',label);document.querySelectorAll('.pipeline span').forEach((e,i)=>e.classList.toggle('active',i<=n));}
function clear(){labDesk.update(null);for(const id of ['#orbit-return','#orbit-dd','#orbit-vol','#orbit-stress'])text(id,'—');for(const id of ['#module-contract','#module-records','#module-source','#module-score'])text(id,'WAITING');$('#module-tape').replaceChildren();$('#finding-list').replaceChildren();text('#scenario-token',$('#contract').value.trim());result=null;frame=0;assembly=0;text('#risk-window','ACQUIRING');text('#risk-note','Waiting for validated history.');for(const s of ['#score','#price','#volume','#change','#drawdown','#records','#risk-return','#risk-dd','#risk-vol','#stress-price'])text(s,'—');text('#verdict','Tracing the evidence…');text('#thought','Waiting for validated price records. No score is generated from the address itself.');text('#name','Resolving contract…');text('#symbol','REQUEST IN PROGRESS');text('#address',$('#contract').value.trim());text('#badge','ACQUIRING');text('#steps','0 / 8');text('#input-time','Input not available yet.');text('#price-time','No current observation');text('#from','—');text('#to','—');$('#features').replaceChildren();$('#limitations').replaceChildren();$('#chart').replaceChildren();$('#score-bar').style.width='0';}
$('#search').onsubmit=async e=>{e.preventDefault();if(busy)return;busy=true;$('#analyze').disabled=true;$('#error').hidden=true;clear();startDecode();setPhase(0,'ACQUIRING OBSERVATIONS');try{const d=await action({type:'research',address:$('#contract').value.trim(),mode:selectedMode});result=d;setPhase(1,'ENCODING FIVE FEATURES');text('#records',d.records);text('#name',d.name||'Unnamed token');text('#symbol',d.symbol||'TOKEN');text('#badge',d.mode==='archive'?'HISTORICAL':'FETCHED HISTORY');text('#source',d.mode==='archive'?'SAVED HISTORY / SEPTEMBER 2026':'BITQUERY / FIRST-RECORD ANALYSIS');text('#token-icon',(d.symbol||'?').slice(0,2).toUpperCase());await delay(paused?0:650);setPhase(2,'PROPAGATING THROUGH 65 REGIONS');for(frame=1;frame<=8;frame++){text('#steps',`${frame} / 8`);await delay(paused?0:260);}frame=8;setPhase(3,'RECONSTRUCTION COMPLETE');paint(d);finishDecode(true);}catch(err){finishDecode(false);result=null;setPhase(0,'DATA UNAVAILABLE');text('#verdict','Not enough evidence.');text('#thought','No model result was produced. Try a saved example or check your data access.');text('#badge','NO RESULT');$('#error').hidden=false;text('#error',err.message);}finally{busy=false;$('#analyze').disabled=false;}};
const usd=n=>Number.isFinite(n)?new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumSignificantDigits:5}).format(n):'—';
function paint(d){labDesk.update(d);if(d.risk){text('#orbit-return',d.risk.observedReturn.toFixed(2)+'%');text('#orbit-dd',d.risk.maxCloseDrawdown.toFixed(2)+'%');text('#orbit-vol',d.risk.volatility===null?'NOT ENOUGH DATA':d.risk.volatility.toFixed(2)+'%');text('#orbit-stress',usd(d.risk.stressPrice));}paintModules(d);addToAtlas(d);text('#scenario-token',(d.name||d.symbol||'Token')+' / '+d.address);const r=d.risk;if(r){text('#risk-return',r.observedReturn.toFixed(2)+'%');text('#risk-dd',r.maxCloseDrawdown.toFixed(2)+'%');text('#risk-vol',r.volatility===null?'INSUFFICIENT':r.volatility.toFixed(2)+'%');text('#stress-price',usd(r.stressPrice));text('#risk-window',r.spanHours.toFixed(1)+'h OBSERVED / '+r.hourlyPairs+' HOURLY PAIRS');text('#risk-note','Close-to-close drawdown excludes intrabar peaks. Volatility requires at least 3 consecutive hourly return pairs. Observed history length is not launch age. The −90% scenario is an assumption, not a model prediction.');}text('#verdict',d.label);text('#thought',d.comment);text('#score',`${(d.score*100).toFixed(1)} / 100`);$('#score-bar').style.width=`${d.score*100}%`;text('#price',usd(d.price));text('#price-time',d.lastTime);text('#volume',usd(d.volume));text('#change',d.inputChange.toFixed(2)+'%');text('#drawdown',d.inputDrawdown.toFixed(2)+'%');text('#input-time','MODEL INPUT / '+d.inputTime+' · FIRST RETURNED HOURLY RECORD');const names=['RETURN','RANGE','VOLUME','POSITION','DRAWDOWN'];$('#features').replaceChildren(...d.features.map((v,i)=>{const box=document.createElement('div'),s=document.createElement('span'),b=document.createElement('b');s.textContent=names[i];b.textContent=v.toFixed(2);box.append(s,b);return box;}));$('#limitations').replaceChildren(...d.limitations.map(v=>{const li=document.createElement('li');li.textContent=v;return li;}));text('#status','COMPLETE / '+new Date(d.checkedAt).toLocaleTimeString('en-GB'));const values=d.candles.map(c=>c.Close).filter(v=>Number.isFinite(v)&&v>0);if(values.length){const logs=values.map(Math.log),lo=Math.min(...logs),hi=Math.max(...logs);const pts=logs.map((v,i)=>`${20+i/Math.max(1,logs.length-1)*760},${140-(v-lo)/Math.max(1e-9,hi-lo)*120}`).join(' ');$('#chart').innerHTML=`<path d="M20 40H780 M20 90H780 M20 140H780" stroke="#262e38" fill="none"/><polyline points="${pts}" fill="none" stroke="#c3d0df" stroke-width="1.5"/>`;text('#from',d.candles[0].time);text('#to',d.candles.at(-1).time+' · LOG PRICE');}}
const canvas=$('#network'),ctx=canvas.getContext('2d');let width=0,height=0,t=0,raf,assembly=0,brainMode='cat',brainSpeed=1;
const resize=new ResizeObserver(()=>{const r=canvas.getBoundingClientRect();width=r.width;height=r.height;const ratio=Math.min(devicePixelRatio,2);canvas.width=width*ratio;canvas.height=height*ratio;ctx.setTransform(ratio,0,0,ratio,0,0);draw();});resize.observe(canvas);
const points=Array.from({length:65},(_,i)=>{const a=i*2.399963,z=1-2*(i+.5)/65,r=Math.sqrt(1-z*z);return [Math.cos(a)*r*1.6,z,Math.sin(a)*r];});
function project(p){const angle=t*.07,c=Math.cos(angle),s=Math.sin(angle),x=p[0]*c+p[2]*s,z=-p[0]*s+p[2]*c,k=Math.min(210,width*.29)/(3.4+z);return [width/2+x*k*1.8,height/2+p[1]*k*1.8,z];}
function draw(){if(!width)return;ctx.clearRect(0,0,width,height);const target=result?(phase===1?.28:phase===2?.28+frame/8*.72:1):(busy?.22:.92);assembly=paused?target:assembly+(target-assembly)*.045;
 const ease=assembly*assembly*(3-2*assembly);
 const resolve=(base,i)=>{const q=project(base),spread=1-ease;return [q[0]+Math.sin(i*9.7)*width*.37*spread,q[1]+Math.cos(i*4.3)*height*.32*spread,q[2]];};
 const p=points.map(resolve);ctx.lineWidth=.5;
 for(let i=0;i<model.edges.length;i++){const [a,b]=model.edges[i],activity=result?Math.abs(result.frames[Math.min(frame,8)][a]):.15;ctx.strokeStyle=i%7===0?'#ef9bcc':'#a8a8bd';ctx.globalAlpha=(.018+activity*.11)*ease;ctx.beginPath();ctx.moveTo(p[a][0],p[a][1]);ctx.lineTo(p[b][0],p[b][1]);ctx.stroke();if(i%15===0&&phase===2){const u=(t*.6+i*.031)%1;ctx.globalAlpha=.8;ctx.fillStyle='#ffc0e4';ctx.fillRect(p[a][0]+(p[b][0]-p[a][0])*u,p[a][1]+(p[b][1]-p[a][1])*u,2.5,2.5);}}
 // Artistic particles visualize acquisition; they are not additional neurons.
 if(brainMode==='cat'){drawResearchCat(resolve,ease);}else{
 // Two folded hemispheres: an artistic brain silhouette, not an anatomical scan.
 for(let i=0;i<3800;i++){const side=i%2?1:-1,n=Math.floor(i/2),a=n*2.399963,z=1-2*(n+.5)/1900,r=Math.sqrt(1-z*z),fold=1+.065*Math.sin(a*8+z*16)*Math.cos(z*19),pulse=1+.012*Math.sin(t*1.8);const base=[side*(.55+Math.cos(a)*r*.54*fold),z*.88*fold,Math.sin(a)*r*.83*fold];const q=resolve(base.map(v=>v*pulse),i),slice=(Math.sin(t*.65)+1)*height/2,highlight=Math.max(0,1-Math.abs(q[1]-slice)/23);ctx.globalAlpha=(.16+(1-q[2])*.2+highlight*.35)*(.3+ease*.7);ctx.fillStyle=highlight>.45||i%9===0?'#f5aed8':'#bec3d3';ctx.fillRect(q[0],q[1],highlight>.5?1.65:1,highlight>.5?1.65:1);}
 }
 drawNeuralOrbits(ease);

 p.forEach(([x,y],i)=>{const v=result?Math.abs(result.frames[Math.min(frame,8)][i]):.1;ctx.globalAlpha=(.3+v*.7)*(.2+ease*.8);ctx.fillStyle=i%3===0?'#ffbce0':'#e0deee';ctx.beginPath();ctx.arc(x,y,1.1+v*2,0,Math.PI*2);ctx.fill();});
 ctx.globalAlpha=.28;ctx.strokeStyle='#cd80b6';const scan=(t*.13)%1;ctx.beginPath();ctx.moveTo(width*.15,height*.2+scan*height*.6);ctx.lineTo(width*.85,height*.2+scan*height*.6);ctx.stroke();ctx.font='8px monospace';ctx.fillStyle='#dfa7cd';ctx.fillText('ASSEMBLY / '+Math.round(ease*100)+'%',width-135,28);ctx.globalAlpha=1;}
function tick(){if(!paused&&!document.hidden&&!$('#token-panel').hidden){t+=.016*brainSpeed;draw();}raf=requestAnimationFrame(tick);}tick();$('#motion').onclick=()=>{paused=!paused;$('#motion').setAttribute('aria-pressed',String(paused));text('#motion',paused?'Resume motion ▷':'Pause motion Ⅱ');draw();};$('#motion').setAttribute('aria-pressed',String(paused));if(paused)text('#motion','Resume motion ▷');window.addEventListener('pagehide',()=>{cancelAnimationFrame(raf);resize.disconnect();});

const tabs=[$('#token-tab'),$('#scenario-tab'),$('#network-tab'),$('#radar-tab')];
function selectTab(index){tabs.forEach((tab,i)=>{const active=i===index;tab.setAttribute('aria-selected',String(active));tab.tabIndex=active?0:-1;document.getElementById(tab.getAttribute('aria-controls')).hidden=!active;});document.body.classList.toggle('radar-active',index===3);text('.top-center',['WORKSPACE 01 / TOKEN RESEARCH','WORKSPACE 02 / SCENARIO LAB','WORKSPACE 03 / TOKEN NETWORK','WORKSPACE 04 / PRO RADAR'][index]);}
tabs.forEach((tab,index)=>{tab.onclick=()=>selectTab(index);tab.onkeydown=e=>{let next;if(e.key==='ArrowRight'||e.key==='ArrowLeft')next=(index+(e.key==='ArrowRight'?1:3))%4;else if(e.key==='Home')next=0;else if(e.key==='End')next=3;else return;e.preventDefault();selectTab(next);tabs[next].focus();};});

// Point typography: visible values are derived from the same text read by assistive technology.
const particleFields=[];
let dustFrame,dustTime=0,dustLast=0;
for(const selector of ['#score','#price','#volume','#change','#drawdown','#risk-return','#risk-dd','#risk-vol','#stress-price']){
 const value=$(selector),host=document.createElement('span'),surface=document.createElement('canvas');
 host.className='particle-value';value.before(host);host.append(value,surface);surface.setAttribute('aria-hidden','true');
 const field={value,host,surface,ctx:surface.getContext('2d'),dots:[],targets:[],w:0,h:0,pointer:null,ready:false};
 const rebuild=()=>{const box=host.getBoundingClientRect();if(!box.width||!box.height)return;field.w=box.width;field.h=box.height;const ratio=Math.min(devicePixelRatio,2);surface.width=box.width*ratio;surface.height=box.height*ratio;field.ctx.setTransform(ratio,0,0,ratio,0,0);
 const label=value.textContent.trim();field.ready=label!=='—'&&label!=='';const mask=document.createElement('canvas');mask.width=Math.ceil(box.width);mask.height=Math.ceil(box.height);const ink=mask.getContext('2d');const size=Math.min(28,box.height*.55,box.width/Math.max(1,label.length)*1.55);ink.font=`500 ${size}px monospace`;ink.textBaseline='middle';ink.fillText(label,1,box.height/2);const pixels=ink.getImageData(0,0,mask.width,mask.height).data,targets=[];
 if(field.ready)for(let y=1;y<mask.height;y+=2)for(let x=1;x<mask.width;x+=2)if(pixels[(y*mask.width+x)*4+3]>70)targets.push({x,y});
 field.targets=targets;const count=Math.max(65,targets.length);field.dots=Array.from({length:count},(_,i)=>field.dots[i]||{x:Math.random()*box.width,y:Math.random()*box.height,vx:0,vy:0,seed:Math.random()*6.28});host.classList.toggle('has-point-result',field.ready);
 };
 const resizeField=new ResizeObserver(rebuild);resizeField.observe(host);const mutation=new MutationObserver(rebuild);mutation.observe(value,{childList:true,characterData:true,subtree:true});
 host.addEventListener('pointermove',e=>{const r=host.getBoundingClientRect();field.pointer={x:e.clientX-r.left,y:e.clientY-r.top};});host.addEventListener('pointerleave',()=>field.pointer=null);
 field.dispose=()=>{resizeField.disconnect();mutation.disconnect();};particleFields.push(field);rebuild();
}
function drawDust(now){const dt=Math.min(2,(now-(dustLast||now))/16.67);dustLast=now;dustTime+=dt*.014;
 for(const f of particleFields){if(!f.host.getClientRects().length)continue;const staticMode=paused||matchMedia('(prefers-reduced-motion: reduce)').matches;f.host.classList.toggle('points-paused',staticMode);if(staticMode||document.hidden)continue;const c=f.ctx;c.clearRect(0,0,f.w,f.h);
 f.dots.forEach((p,i)=>{const target=f.targets[i%Math.max(1,f.targets.length)];let tx,ty;if(target){tx=target.x;ty=target.y;}else{tx=(.5+.43*Math.sin(dustTime*.45+p.seed+i*.2))*f.w;ty=(.5+.34*Math.cos(dustTime*.7+p.seed*2))*f.h;}
 let ax=(tx-p.x)*.045,ay=(ty-p.y)*.045;if(f.pointer){const dx=p.x-f.pointer.x,dy=p.y-f.pointer.y,d=Math.hypot(dx,dy);if(d<55){const force=(1-d/55)*2.8;ax+=dx/Math.max(1,d)*force;ay+=dy/Math.max(1,d)*force;}}
 p.vx=(p.vx+ax*dt)*.77;p.vy=(p.vy+ay*dt)*.77;p.x+=p.vx*dt;p.y+=p.vy*dt;
 c.fillStyle=i%4===0?'#f0add2':'#d4d3df';c.globalAlpha=target?.9:.2+.35*(.5+.5*Math.sin(p.seed+dustTime));c.beginPath();c.ellipse(p.x,p.y,target?.85:1.7,target?.85:.65,p.seed+dustTime,0,Math.PI*2);c.fill();});c.globalAlpha=1;
 }dustFrame=requestAnimationFrame(drawDust);
}dustFrame=requestAnimationFrame(drawDust);
window.addEventListener('pagehide',()=>{cancelAnimationFrame(dustFrame);particleFields.forEach(f=>f.dispose());});

// A 15-second local introduction, not a network download or model-training claim.
const boot=$('#boot'),bootCanvas=$('#boot-cat'),bootCtx=bootCanvas.getContext('2d');
const bootLabels=[['catbrain --boot --local','runtime / local workspace'],['mount ./cortex-data.mjs','bundled connectivity / available'],['cortex inspect --regions','65 cortical areas / engineered dynamics'],['graph index --directed','1,139 directed links / indexed'],['readout load --weights','trained output layer / available'],['features register --ohlcv','return · range · volume · position · drawdown'],['observations prepare --readonly','provider requests / on demand'],['history register --archive','saved observations / local'],['renderer init --point-cloud','silver particles / rose connections'],['atlas register --similarity','five-feature comparison / session graph'],['radar register --filters','freshness · liquidity · activity · change'],['portrait assemble --face','point reconstruction / resolving'],['mascot reveal --curious','right edge / rose mesh'],['mascot reveal --peek','lower edge / rounded silhouette'],['workspace ready --await-key','all desks available / press any key']];
const bootRows=bootLabels.map(([label,detail],i)=>{const row=document.createElement('div');row.className='boot-row';row.hidden=true;const command=document.createElement('div'),a=document.createElement('span'),b=document.createElement('b'),note=document.createElement('small');a.textContent='$ '+label;command.append(a,b);note.textContent='  ↳ '+detail;const trace=document.createElement('small');trace.className='boot-trace';trace.textContent='  ['+String(i).padStart(2,'0')+'] resolve → bind → stage / local';const line=document.createElement('small');line.className='boot-trace';line.textContent='  '+(i<5?'cortex :: bundled graph + readout':i<10?'render :: buffers / layers / point field':'workspace :: routes / panels / interaction');row.append(command,note,trace,line);$('#boot-lines').append(row);return row;});
let bootLogStep=-1;
let bootReady=false;let bootPoints=[],bw=0,bh=0,bootRaf,bootStart=performance.now(),bootClosed=false;
function seedPortrait(){const rect=bootCanvas.parentElement.getBoundingClientRect();bw=rect.width;bh=rect.height;const dpr=Math.min(devicePixelRatio,2);bootCanvas.width=bw*dpr;bootCanvas.height=bh*dpr;bootCtx.setTransform(dpr,0,0,dpr,0,0);
 const mask=document.createElement('canvas');mask.width=620;mask.height=640;const m=mask.getContext('2d');m.translate(310,375);
 // Continuous silhouette: long ears, tilted head, and a curved body peeking from the right.
 m.fillStyle='#636363';
 m.beginPath();m.moveTo(-133,-24);m.bezierCurveTo(-155,-83,-126,-254,-108,-271);m.lineTo(-44,-130);m.bezierCurveTo(-13,-140,24,-140,53,-124);m.lineTo(112,-279);m.bezierCurveTo(147,-245,159,-105,137,-31);m.bezierCurveTo(158,40,120,113,25,117);m.bezierCurveTo(-78,118,-145,75,-133,-24);m.fill();
 m.fillStyle='#eeeeee';for(const [x,y] of [[-60,-9],[60,-9]]){m.beginPath();m.ellipse(x,y,35,48,-.08,0,Math.PI*2);m.fill();}m.fillStyle='#080808';for(const [x,y] of [[-55,-8],[55,-8]]){m.beginPath();m.ellipse(x,y,10,22,-.12,0,Math.PI*2);m.fill();}m.fillStyle='#bbbbbb';m.beginPath();m.ellipse(5,32,9,5,0,0,Math.PI*2);m.fill();m.strokeStyle='#aaaaaa';m.lineWidth=1;for(let i=0;i<3;i++){m.beginPath();m.moveTo(-104,28+i*14);m.lineTo(-207,10+i*35);m.stroke();m.beginPath();m.moveTo(113,18+i*13);m.lineTo(221,-5+i*32);m.stroke();}
 const pixels=m.getImageData(0,0,620,640).data;bootPoints=[];const scale=Math.min(bw/600,bh/610)*.95,ox=(bw-620*scale)/2,oy=(bh-640*scale)/2;
 for(let y=0;y<640;y+=3)for(let x=0;x<620;x+=3){const at=(y*620+x)*4;if(pixels[at+3]>50&&pixels[at]>20){const bright=pixels[at]/255,seed=Math.sin(x*12.9898+y*78.233)*43758.5453,rand=seed-Math.floor(seed);bootPoints.push({x:ox+x*scale,y:oy+y*scale,bright,rand,sx:bw*(.5+.65*Math.sin(seed)),sy:bh*(.5+.65*Math.cos(seed*2))});}}
}
const bootResize=new ResizeObserver(seedPortrait);
function closeBoot(){if(bootClosed)return;bootClosed=true;cancelAnimationFrame(bootRaf);bootResize.disconnect();boot.close();$('#contract').focus();}
function animateBoot(now){if(bootClosed)return;const progress=Math.min(1,(now-bootStart)/15000),assembly=Math.min(1,progress/ .88),ease=assembly*assembly*(3-2*assembly);bootCtx.clearRect(0,0,bw,bh);
 for(let i=0;i<bootPoints.length;i++){const p=bootPoints[i],local=Math.max(0,Math.min(1,(ease-p.rand*.25)/.75)),blend=local*local*(3-2*local),x=p.sx+(p.x-p.sx)*blend,y=p.sy+(p.y-p.sy)*blend;bootCtx.globalAlpha=(.12+p.bright*.8)*(.25+.75*local);bootCtx.fillStyle=i%9===0?'#eba5d0':'#e0dfe7';bootCtx.beginPath();bootCtx.arc(x,y,p.bright>.7?1.05:.65,0,Math.PI*2);bootCtx.fill();if(i%23===0&&local>.8){const q=bootPoints[Math.min(i+21,bootPoints.length-1)];if(Math.hypot(q.x-p.x,q.y-p.y)<30){bootCtx.globalAlpha=.16*local;bootCtx.strokeStyle='#e6a4d0';bootCtx.lineWidth=.5;bootCtx.beginPath();bootCtx.moveTo(x,y);bootCtx.lineTo(q.x,q.y);bootCtx.stroke();}}}
 bootCtx.globalAlpha=1;drawPeekCats((now-bootStart)/1000);const step=Math.min(15,Math.floor(progress*15));if(step!==bootLogStep){bootLogStep=step;bootRows.forEach((r,i)=>{r.hidden=i>step;r.className='boot-row '+(i<step?'done':i===step?'current':'');r.firstChild.lastChild.textContent=i<step?'[ READY ]':'[ INIT ]';});const log=$('#boot-lines');log.scrollTop=log.scrollHeight;}text('#boot-percent',String(Math.floor(progress*100)).padStart(2,'0')+'%');$('#boot-bar').style.width=progress*100+'%';text('#boot-phase',progress<.25?'SEEDING':progress<.75?'ASSEMBLING':'RESOLVING');if(progress>=1){bootReady=true;text('#boot-phase','READY');text('#boot-enter','PRESS ANY KEY TO ENTER');$('#boot-skip').textContent='Enter terminal ↗';}bootRaf=requestAnimationFrame(animateBoot);}
$('#boot-skip').onclick=closeBoot;boot.addEventListener('cancel',e=>{e.preventDefault();closeBoot();});boot.showModal();bootResize.observe(bootCanvas.parentElement);seedPortrait();
if(matchMedia('(prefers-reduced-motion: reduce)').matches){bootStart=performance.now()-15000;animateBoot(performance.now());cancelAnimationFrame(bootRaf);}else{bootRaf=requestAnimationFrame(animateBoot);}
window.addEventListener('pagehide',()=>{cancelAnimationFrame(bootRaf);bootResize.disconnect();});

function bootKey(e){if(!boot.open||!bootReady||e.ctrlKey||e.metaKey||e.altKey||['Shift','Control','Alt','Meta'].includes(e.key))return;e.preventDefault();closeBoot();}
document.addEventListener('keydown',bootKey);window.addEventListener('pagehide',()=>document.removeEventListener('keydown',bootKey));
function drawPeekCats(seconds){
 if(!drawPeekCats.meshes){drawPeekCats.meshes=[0,1,2].map(kind=>{const mask=document.createElement('canvas');mask.width=360;mask.height=400;const m=mask.getContext('2d');m.translate(165,220);m.fillStyle='#999';m.beginPath();
 if(kind===0){m.moveTo(-70,-10);m.bezierCurveTo(-91,-50,-79,-154,-64,-177);m.lineTo(-24,-82);m.quadraticCurveTo(10,-92,37,-77);m.lineTo(75,-174);m.quadraticCurveTo(107,-90,82,-12);m.bezierCurveTo(92,35,64,60,38,69);m.bezierCurveTo(76,112,155,102,199,63);m.lineTo(199,144);m.bezierCurveTo(91,183,14,106,-23,72);m.bezierCurveTo(-69,71,-86,29,-70,-10);}
 else if(kind===1){m.moveTo(-96,-15);m.lineTo(-106,-38);m.lineTo(-94,-40);m.lineTo(-88,-154);m.lineTo(-41,-87);m.quadraticCurveTo(0,-104,37,-87);m.lineTo(82,-169);m.lineTo(94,-48);m.lineTo(107,-38);m.lineTo(96,-30);m.bezierCurveTo(111,40,66,80,24,83);m.lineTo(48,122);m.lineTo(77,127);m.quadraticCurveTo(104,103,114,136);m.lineTo(113,156);m.lineTo(-107,156);m.quadraticCurveTo(-105,117,-78,132);m.lineTo(-49,114);m.lineTo(-31,79);m.bezierCurveTo(-78,76,-111,39,-96,-15);}
 else{m.moveTo(-99,-16);m.lineTo(-106,-170);m.quadraticCurveTo(-67,-172,-33,-78);m.quadraticCurveTo(0,-89,34,-76);m.lineTo(128,-148);m.quadraticCurveTo(128,-76,92,-19);m.bezierCurveTo(109,48,60,78,25,91);m.lineTo(41,150);m.lineTo(-42,150);m.lineTo(-31,90);m.bezierCurveTo(-79,72,-114,29,-99,-16);}
 m.closePath();m.fill();m.fillStyle='#fff';for(const x of [-37,37]){m.beginPath();m.ellipse(x,kind===0?-6:0,kind===1?28:25,kind===2?7:32,kind===2?(x<0?.12:-.12):0,0,Math.PI*2);m.fill();}m.fillStyle='#050505';for(const x of [-33,41]){m.beginPath();m.ellipse(x,0,kind===0?7:5,kind===2?7:18,0,0,Math.PI*2);m.fill();}m.fillStyle='#ddd';m.beginPath();m.moveTo(-7,27);m.lineTo(7,27);m.lineTo(0,34);m.closePath();m.fill();if(kind===2){m.beginPath();m.ellipse(0,57,13,7,0,0,Math.PI*2);m.fill();}m.strokeStyle='#ddd';m.lineWidth=1;for(let j=0;j<3;j++){m.beginPath();m.moveTo(-70,17+j*10);m.lineTo(-140,5+j*25);m.moveTo(75,17+j*10);m.lineTo(151,5+j*25);m.stroke();}
 const data=m.getImageData(0,0,360,400).data,points=[];for(let y=0;y<400;y+=3)for(let x=0;x<360;x+=3){const v=data[(y*360+x)*4];if(data[(y*360+x)*4+3]>40&&v>20)points.push({x:x-165+Math.sin(y*x)*.55,y:y-220+Math.cos(x*y)*.55,eye:v>200});}return points;});}
 for(let kind=0;kind<3;kind++){const start=[11.6,13,14][kind];if(seconds<start)continue;const u=Math.min(1,(seconds-start)/.38),rise=1-(1-u)**3,size=Math.min(bw*.29,185),x=[bw-size*.34,bw*.19,bw*.53][kind],y=bh+size*(1-rise)-size*.28;bootCtx.save();bootCtx.translate(x,y);bootCtx.rotate(kind===0?-.45:kind===1?.04:-.1);bootCtx.scale(size/200,size/200);const points=drawPeekCats.meshes[kind];for(let i=0;i<points.length;i++){const p=points[i];bootCtx.globalAlpha=p.eye?.95:.7;bootCtx.fillStyle=p.eye?'#ffe3f2':'#e7a0ca';bootCtx.beginPath();bootCtx.arc(p.x,p.y,p.eye?1.2:.8,0,Math.PI*2);bootCtx.fill();if(i%4===0){for(const j of [i+1,i+31]){const q=points[j];if(q&&Math.hypot(q.x-p.x,q.y-p.y)<18){bootCtx.globalAlpha=.25;bootCtx.strokeStyle='#f0a5d2';bootCtx.lineWidth=.5;bootCtx.beginPath();bootCtx.moveTo(p.x,p.y);bootCtx.lineTo(q.x,q.y);bootCtx.stroke();}}}}bootCtx.restore();}
}

const atlasDesk=initAtlas(action,model);
function addToAtlas(d){atlasDesk.add(d);}
const labDesk=initLab();
const radarDesk=initRadar();

let radarState=null,radarSelected=null,radarPolling=false,radarRequest=false,radarKnown=new Set();
async function pollRadar(){if(radarPolling||$('#radar-panel').hidden||!session)return;radarPolling=true;try{const r=await fetch('/api/state',{headers:{'x-sheriff-session':session}});if(!r.ok)throw Error('Local radar session unavailable');radarState=await r.json();renderRadar();}catch(e){text('#radar-error',e.message);}finally{radarPolling=false;}}
function renderRadar(){const s=radarState;if(!s)return;radarDesk.update(s);text('#radar-status',(s.demo?'DEMO / SIMULATED · ':'')+s.status);text('#radar-scan',s.lastScan?'LAST SCAN '+new Date(s.lastScan).toLocaleTimeString('en-GB'):'NO SCAN YET');const tokens=s.tokens.slice(0,120),freshIds=new Set(tokens.map(t=>t.address));if(!tokens.some(t=>t.address===radarSelected))radarSelected=tokens[0]?.address;$('#radar-empty').hidden=tokens.length>0;
 $('#radar-rows').replaceChildren(...tokens.map(t=>{const a=s.activity?.find(a=>a.address===t.address),tr=document.createElement('tr');tr.className=(t.address===radarSelected?'selected ':'')+(!radarKnown.has(t.address)?'new-row':'');const cell=document.createElement('td'),b=document.createElement('button'),sub=document.createElement('small');b.textContent=t.symbol||t.name||'Unresolved';sub.textContent=t.address.slice(0,8)+'…'+t.address.slice(-6);b.append(sub);b.onclick=()=>{radarSelected=t.address;renderRadar();};cell.append(b);tr.append(cell);const m=t.market,age=m?.observedAt?Math.max(0,Math.floor((Date.now()-m.observedAt)/1000)):null;for(const v of [usd(m?.price),usd(m?.liquidity),usd(m?.volume),Number.isFinite(m?.change)?m.change.toFixed(1)+'%':'—',age===null?'UNKNOWN':age+'s',a?.verdict||'WAIT']){const td=document.createElement('td');td.textContent=v;tr.append(td);}return tr;}));radarKnown=freshIds;
 const token=tokens.find(t=>t.address===radarSelected),a=s.activity?.find(a=>a.address===radarSelected);$('#radar-analyze').disabled=!token;text('#radar-name',token?.name||token?.symbol||'Watching for evidence.');text('#radar-verdict',a?.verdict||'WAIT');text('#radar-reason',a?.reason||'No verified market quote.');$('#radar-checks').replaceChildren(...(a?.checks||[]).map(check=>{const div=document.createElement('div');div.textContent=`${check.pass===true?'PASS':check.pass===false?'REVIEW':'UNKNOWN'} / ${check.name} · ${check.detail}`;return div;}));$('#radar-events').replaceChildren(...(s.engine?.events||[]).slice(0,10).map(e=>{const div=document.createElement('div');div.textContent=new Date(e.at).toLocaleTimeString('en-GB')+' / '+e.symbol+' / '+e.text;return div;}));
}
async function radarAction(body){if(radarRequest)return;radarRequest=true;text('#radar-error','Requesting provider…');try{await action(body);text('#radar-error','');await pollRadar();}catch(e){text('#radar-error',e.message);}finally{radarRequest=false;}}
$('#radar-connect').onsubmit=e=>{e.preventDefault();const key=$('#scout-key').value;$('#scout-key').value='';radarAction({type:'connect',key});};$('#radar-refresh').onclick=()=>radarAction({type:'refresh'});$('#radar-analyze').onclick=()=>{if(!radarSelected)return;$('#contract').value=radarSelected;selectedMode='live';selectTab(0);$('#search').requestSubmit();};
const radarTimer=setInterval(()=>{if($('#radar-panel').hidden)return;text('#radar-clock','DISPLAY / '+new Date().toLocaleTimeString('en-GB'));pollRadar();},1000);
window.addEventListener('pagehide',()=>{clearInterval(radarTimer);});

function drawNeuralOrbits(ease){
 ctx.save();const cx=width/2,cy=height/2,rx=Math.min(width*.38,250),ry=height*.34;
 if(brainMode!=='cortex'){for(let ring=0;ring<4;ring++){ctx.strokeStyle=ring%2?'#be8daa':'#8f8baf';ctx.globalAlpha=.18;ctx.lineWidth=.65;ctx.beginPath();ctx.ellipse(cx,cy,rx+ring*7,ry*.45+ring*12,(ring-2)*.28,0,Math.PI*2);ctx.stroke();for(let j=0;j<48;j++){const a=j/48*Math.PI*2+t*(ring%2?.15:-.12);ctx.globalAlpha=j%8===0?.65:.16;ctx.fillStyle='#efbbdc';ctx.fillRect(cx+Math.cos(a)*(rx+ring*7),cy+Math.sin(a)*(ry*.45+ring*12),j%8===0?2:1,1);}}}
 if(brainMode==='scan'){const y=cy+Math.sin(t*.5)*ry;const glow=ctx.createLinearGradient(0,y-22,0,y+22);glow.addColorStop(0,'#eaa6cf00');glow.addColorStop(.5,'#eaa6cf18');glow.addColorStop(1,'#eaa6cf00');ctx.fillStyle=glow;ctx.globalAlpha=1;ctx.fillRect(cx-rx,y-22,rx*2,44);}
 ctx.font='8px monospace';ctx.fillStyle='#be91ad';ctx.globalAlpha=.7;ctx.fillText('L / CORTEX',18,68);ctx.fillText('R / CORTEX',width-83,68);ctx.fillText('ARTISTIC MORPHOLOGY',18,height-47);
 // The bars display model activations only after observations are available.
 const values=result?.frames?.[Math.min(frame,8)];for(let i=0;i<32;i++){const v=values?Math.abs(values[i]):0;ctx.fillStyle=i%3?'#92839c':'#e8acd1';ctx.globalAlpha=values?.65:.12;ctx.fillRect(18+i*3,height-62,1.5,-(values?v*28:3));}ctx.restore();
}
for(const button of document.querySelectorAll('[data-brain-mode]'))button.onclick=()=>{brainMode=button.dataset.brainMode;document.querySelectorAll('[data-brain-mode]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));draw();};
$('#brain-speed').onclick=()=>{brainSpeed=brainSpeed===1?.4:1;$('#brain-speed').textContent=brainSpeed===1?'Motion 1×':'Motion 0.4×';};

function paintModules(d){text('#module-contract',d.symbol||d.address.slice(0,10));text('#module-records',d.records+' RECORDS');text('#module-source',d.mode==='archive'?'SAVED HISTORY':'BITQUERY HISTORY');text('#module-score',(d.score*100).toFixed(1)+' / 100');const bars=d.candles.slice(-32),max=Math.max(...bars.map(c=>c.volume),1);$('#module-tape').replaceChildren(...bars.map(c=>{const b=document.createElement('i');b.style.height=(4+c.volume/max*24)+'px';b.title='Observed volume: '+usd(c.volume);return b;}));
 const findings=[['01','INPUT CANDLE',d.inputChange.toFixed(2)+'%',d.inputTime+' / first returned record',Math.min(100,Math.abs(d.inputChange))],['02','HIGH TO CLOSE',d.inputDrawdown.toFixed(2)+'%','Distance from the input candle high',Math.min(100,Math.abs(d.inputDrawdown))],['03','OBSERVED VOLUME',usd(d.volume),'Sum of '+d.records+' returned records',null],['04','MODEL READOUT',(d.score*100).toFixed(1)+' / 100',d.label+' / not a calibrated probability',d.score*100],['05','CONTRACT SAFETY','UNKNOWN','Holder concentration, creator permissions and liquidity locks are not checked',null]];
 $('#finding-list').replaceChildren(...findings.map(([n,label,value,detail,level])=>{const row=document.createElement('article'),index=document.createElement('span'),content=document.createElement('div'),title=document.createElement('strong'),amount=document.createElement('b'),note=document.createElement('small');index.textContent=n;title.textContent=label;amount.textContent=value;note.textContent=detail;content.append(title,note);if(level!==null){const bar=document.createElement('div'),fill=document.createElement('i');bar.className='finding-bar';fill.style.width=level+'%';bar.append(fill);content.append(bar);}row.append(index,content,amount);return row;}));
}
function drawResearchCat(resolve,ease){
 if(!drawResearchCat.cloud){const m=document.createElement('canvas');m.width=320;m.height=360;const c=m.getContext('2d');c.translate(160,205);c.fillStyle='#999';c.beginPath();c.moveTo(-100,-16);c.lineTo(-91,-179);c.lineTo(-34,-98);c.quadraticCurveTo(0,-112,36,-97);c.lineTo(93,-179);c.lineTo(103,-14);c.bezierCurveTo(117,68,59,112,0,112);c.bezierCurveTo(-70,108,-113,59,-100,-16);c.fill();c.fillStyle='#fff';for(const x of [-43,43]){c.beginPath();c.ellipse(x,7,28,35,0,0,Math.PI*2);c.fill();}c.fillStyle='#000';for(const x of [-39,39]){c.beginPath();c.ellipse(x,8,9,18,0,0,Math.PI*2);c.fill();}c.fillStyle='#eee';c.beginPath();c.moveTo(-7,44);c.lineTo(7,44);c.lineTo(0,52);c.fill();const pixels=c.getImageData(0,0,320,360).data;drawResearchCat.cloud=[];for(let y=0;y<360;y+=3)for(let x=0;x<320;x+=3){const v=pixels[(y*320+x)*4];if(pixels[(y*320+x)*4+3]>50&&v>20)drawResearchCat.cloud.push({x:(x-160)/95,y:(y-180)/120,z:.2*Math.cos((x-160)/90),bright:v>200});}}
 const cloud=drawResearchCat.cloud;for(let i=0;i<cloud.length;i++){const v=cloud[i],q=resolve([v.x,v.y,v.z+.025*Math.sin(t+i*.17)],i);ctx.fillStyle=v.bright?'#f9dfed':i%7?'#bfabc0':'#ef9fce';ctx.globalAlpha=(v.bright?.9:.48)*(.3+ease*.7);ctx.beginPath();ctx.arc(q[0],q[1],v.bright?1.05:.7,0,Math.PI*2);ctx.fill();}
 for(let i=0;i<6;i++){const a=(i/6)*Math.PI*2-Math.PI/2,x=width/2+Math.cos(a)*width*.4,y=height/2+Math.sin(a)*height*.4;ctx.strokeStyle='#c388b0';ctx.globalAlpha=.22;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(width/2+Math.cos(a)*65,height/2+Math.sin(a)*85);ctx.stroke();const u=(t*.35+i*.17)%1;ctx.globalAlpha=.8;ctx.fillStyle='#f3b5da';ctx.fillRect(x+(width/2-x)*u,y+(height/2-y)*u,2,2);ctx.font='8px monospace';ctx.fillText(['RESOLVE','OBSERVE','SOURCE','ENCODE','PROPAGATE','READOUT'][i],x-20,y-7);}
 ctx.globalAlpha=1;
}

const formulaCanvas=$('#formula-brain'),formulaCtx=formulaCanvas.getContext('2d');let fw=0,fh=0,formulaRaf,formulaTime=0,formulaPaused=matchMedia('(prefers-reduced-motion: reduce)').matches;
const formulaResize=new ResizeObserver(()=>{const r=formulaCanvas.getBoundingClientRect();fw=r.width;fh=r.height;const ratio=Math.min(devicePixelRatio,2);formulaCanvas.width=fw*ratio;formulaCanvas.height=fh*ratio;formulaCtx.setTransform(ratio,0,0,ratio,0,0);paintFormula();});formulaResize.observe(formulaCanvas);
function paintFormula(){if(!fw)return;const c=formulaCtx;c.clearRect(0,0,fw,fh);const cx=fw/2,cy=fh*.43,scale=Math.min(fw*.16,140);drawScientificPlate(c,cx,cy,scale,formulaTime,fw,fh);const center=[$('.fn-return'),$('.fn-drawdown'),$('.fn-volatility'),$('.fn-stress')].map(el=>{const a=el.querySelector('.formula-circle').getBoundingClientRect(),b=formulaCanvas.getBoundingClientRect();return {x:a.x-b.x+a.width/2,y:a.y-b.y+a.height/2};});
 for(let k=0;k<center.length;k++){const p=center[k];c.globalAlpha=.28;c.strokeStyle=k%2?'#a6a1be':'#eaa6cf';c.setLineDash([3,7]);c.beginPath();c.moveTo(cx,cy);c.lineTo(p.x,p.y);c.stroke();c.setLineDash([]);for(let j=0;j<10;j++){const u=(formulaTime*.12+j/10)%1;c.globalAlpha=.3+.6*u;c.fillStyle='#edb5d9';c.beginPath();c.arc(cx+(p.x-cx)*u,cy+(p.y-cy)*u,1.4,0,Math.PI*2);c.fill();}}
 c.globalAlpha=.2;c.strokeStyle='#ca91b8';c.beginPath();c.ellipse(cx,cy,scale*1.4,scale*.95,0,0,Math.PI*2);c.stroke();
 for(let i=0;i<2600;i++){const side=i%2?1:-1,n=Math.floor(i/2),a=n*2.399963,z=1-2*(n+.5)/1300,r=Math.sqrt(1-z*z),fold=1+.055*Math.sin(a*9+z*20);let x=side*(.5+Math.cos(a)*r*.48*fold),y=z*.85,depth=Math.sin(a)*r*.7;const angle=Math.sin(formulaTime*.2)*.24,rx=x*Math.cos(angle)+depth*Math.sin(angle),rz=-x*Math.sin(angle)+depth*Math.cos(angle);c.globalAlpha=.18+(1-rz)*.3;c.fillStyle=i%7?'#cfbdcf':'#efa3d0';c.fillRect(cx+rx*scale,cy+y*scale,1,1);}
 c.globalAlpha=1;
}
function formulaTick(){if(!$('#scenario-panel').hidden&&!document.hidden){if(!formulaPaused&&!paused)formulaTime+=.016;paintFormula();}formulaRaf=requestAnimationFrame(formulaTick);}formulaTick();
function syncFormulaMotion(){$('.formula-universe').classList.toggle('motion-stopped',formulaPaused);$('#formula-motion').setAttribute('aria-pressed',String(formulaPaused));text('#formula-motion',formulaPaused?'Resume motion ▷':'Pause motion Ⅱ');}syncFormulaMotion();$('#formula-motion').onclick=()=>{formulaPaused=!formulaPaused;syncFormulaMotion();};window.addEventListener('pagehide',()=>{cancelAnimationFrame(formulaRaf);formulaResize.disconnect();});

// Decorative binary reconstruction follows request state; snippets are not executed.
const decodeCanvas=document.createElement('canvas');decodeCanvas.id='decode-field';decodeCanvas.setAttribute('aria-hidden','true');document.body.append(decodeCanvas);const decodeCtx=decodeCanvas.getContext('2d');let decodeRaf,decodeActive=false,decodeStart=0,decodeEnd=0,decodeW=0,decodeH=0;
function sizeDecode(){const ratio=Math.min(devicePixelRatio,2);decodeW=innerWidth;decodeH=innerHeight;decodeCanvas.width=decodeW*ratio;decodeCanvas.height=decodeH*ratio;decodeCtx.setTransform(ratio,0,0,ratio,0,0);}
window.addEventListener('resize',sizeDecode);sizeDecode();
function startDecode(){cancelAnimationFrame(decodeRaf);decodeStart=performance.now();decodeEnd=0;decodeActive=true;decodeCanvas.hidden=paused||matchMedia('(prefers-reduced-motion: reduce)').matches;document.body.classList.remove('decode-reveal');document.body.classList.add('is-decoding');if(decodeCanvas.hidden){document.body.classList.remove('is-decoding');return;}decodeRaf=requestAnimationFrame(paintDecode);}
function finishDecode(success){document.body.classList.remove('is-decoding');document.body.classList.toggle('decode-reveal',success);if(!success){decodeActive=false;decodeCanvas.hidden=true;cancelAnimationFrame(decodeRaf);return;}decodeEnd=performance.now();}
function paintDecode(now){if(!decodeActive)return;const elapsed=Math.max(0,(now-decodeStart)/1000),fade=decodeEnd?Math.max(0,1-(now-decodeEnd)/1400):1;if(!fade){decodeActive=false;decodeCanvas.hidden=true;return;}const c=decodeCtx;c.clearRect(0,0,decodeW,decodeH);const top=Math.max(90,Math.min(decodeH*.4,document.querySelector('#search').getBoundingClientRect().bottom+20));c.save();c.beginPath();c.rect(0,top,decodeW,decodeH-top);c.clip();
 const panel=document.querySelector('.workspace').getBoundingClientRect();c.fillStyle='#09070d';c.globalAlpha=.38*fade;c.fillRect(0,top,decodeW,decodeH-top);
 for(let col=0;col<Math.ceil(decodeW/25);col++){const speed=22+(col%7)*13,offset=(elapsed*speed+col*61)%(decodeH+180);for(let row=0;row<20;row++){const y=offset-row*22;if(y<top||y>decodeH)continue;const bit=(col*17+row*7+Math.floor(elapsed*3))%3===0?'1':'0';c.font=(col%6===0?19:10)+'px monospace';c.globalAlpha=fade*(.08+.42*(1-row/20));c.fillStyle=row===0?'#ffe1f2':'#e799ce';c.fillText(bit,col*25+Math.sin(elapsed*.4+col)*7,y);}}
 const snippets=['observe(contract) → await records','encode(OHLC, volume) → x[5]','h[t+1] = tanh(Wx + Ah[t])','cortex.regions = 65','graph.edges = 1139','readout(h) → raw_score','source.timestamp → retained','missing_data → unknown'];
 for(let k=0;k<7;k++){const x=24+(k*211)%Math.max(100,decodeW-240),y=top+45+((k*97+elapsed*9)%Math.max(100,decodeH-top-50));c.font='9px monospace';c.globalAlpha=.32*fade;c.fillStyle='#d6a6ce';const line=snippets[(k+Math.floor(elapsed))%snippets.length];c.fillText(line.slice(0,Math.floor((elapsed%2)/2*line.length)+10),x,y);}
 c.restore();decodeRaf=requestAnimationFrame(paintDecode);
}
decodeCanvas.hidden=true;window.addEventListener('pagehide',()=>{cancelAnimationFrame(decodeRaf);window.removeEventListener('resize',sizeDecode);});

// Point-cloud heights encode available magnitudes, not wallet relationships or future prices.
const terrainCanvas=$('#terrain'),terrainCtx=terrainCanvas.getContext('2d');let tw=0,th=0,terrainYaw=-.3,terrainTilt=.6,terrainZoom=1,terrainMode='cortex',terrainPause=matchMedia('(prefers-reduced-motion: reduce)').matches,terrainTime=0,terrainRaf,terrainPointer=null,terrainData=null,terrainValues=[];
const terrainResize=new ResizeObserver(()=>{const r=terrainCanvas.getBoundingClientRect();tw=r.width;th=r.height;const ratio=Math.min(devicePixelRatio,2);terrainCanvas.width=tw*ratio;terrainCanvas.height=th*ratio;terrainCtx.setTransform(ratio,0,0,ratio,0,0);drawTerrain();});terrainResize.observe(terrainCanvas);
function terrainInput(){if(terrainData===result)return;terrainData=result;terrainValues=result?(terrainMode==='cortex'?result.frames[8].map(Math.abs):result.candles.map(c=>Math.abs(Math.log(c.Close/c.Open)))):[];if(terrainValues.length>80)terrainValues=Array.from({length:80},(_,i)=>terrainValues[Math.floor(i*(terrainValues.length-1)/79)]);text('#terrain-status',result?(result.mode==='archive'?'HISTORICAL INPUT':'FETCHED INPUT'):'AWAITING OBSERVATIONS');text('#terrain-count',result?(terrainMode==='cortex'?'65 REGIONS / STEP 8':result.records+' RECORDS / SAMPLED BY INDEX'):'NO INPUT');text('#terrain-note',terrainMode==='cortex'?'Height encodes absolute final-region activation; placement and depth are artistic. Scan motion does not change model values.':'Height encodes absolute log(close/open) per observed candle. Index spacing is not elapsed time; up to 80 records shown. Surface between samples is decorative.');}
function drawTerrain(){if(!tw)return;terrainInput();const c=terrainCtx;c.clearRect(0,0,tw,th);const count=terrainValues.length,max=Math.max(...terrainValues,1e-8),cols=88,rows=38,scale=Math.min(tw*.43,360)*terrainZoom,co=Math.cos(terrainYaw),si=Math.sin(terrainYaw);const project=(x,z,h)=>{const rx=x*co-z*si,rz=x*si+z*co;return [tw/2+rx*scale,th*.67+rz*scale*.31-h*scale*terrainTilt];};let prev=[];
 for(let row=0;row<rows;row++){const z=row/(rows-1)*1.55-.775,current=[];for(let col=0;col<cols;col++){const x=col/(cols-1)*2-1,position=col/(cols-1)*Math.max(0,count-1),index=Math.floor(position),mix=position-index,value=count?((terrainValues[index]||0)*(1-mix)+(terrainValues[Math.min(index+1,count-1)]||0)*mix)/max:0;const ridge=Math.exp(-z*z*5),h=value*ridge*.78+(count?.025:0)*Math.sin(col*.4+row*.3);const p=project(x,z,h),wave=Math.max(0,1-Math.abs(x-Math.sin(terrainTime*.35))/.09);current.push(p);c.fillStyle=wave>.4?'#f8b8dd':row%5===0?'#dda6cf':'#b7b3c7';c.globalAlpha=count?.22+value*.42+wave*.25:.12;c.beginPath();c.arc(p[0],p[1],wave>.5?1.2:.7,0,Math.PI*2);c.fill();if(col&&row%3===0){c.globalAlpha=.12+wave*.15;c.strokeStyle='#a993ad';c.lineWidth=.5;c.beginPath();c.moveTo(current[col-1][0],current[col-1][1]);c.lineTo(p[0],p[1]);c.stroke();}if(prev[col]&&col%8===0){c.globalAlpha=.12;c.beginPath();c.moveTo(prev[col][0],prev[col][1]);c.lineTo(p[0],p[1]);c.stroke();}}prev=current;}
 c.globalAlpha=.45;c.strokeStyle='#aa849c';c.lineWidth=.6;for(const [x,y,dx,dy] of [[18,42,1,1],[tw-18,42,-1,1],[18,th-40,1,-1],[tw-18,th-40,-1,-1]]){c.beginPath();c.moveTo(x,y+dy*14);c.lineTo(x,y);c.lineTo(x+dx*14,y);c.stroke();}c.font='8px monospace';c.fillStyle='#bea6bb';c.fillText('AMPLITUDE / NORMALIZED',25,68);c.fillText(count?'PEAK '+max.toFixed(4):'NO MEASURED ACTIVITY',25,83);for(let i=0;i<12;i++){c.globalAlpha=.2;c.fillRect(tw-35,80+i*16,8,1);}
 c.globalAlpha=1;
}
function terrainTick(){if(!$('#token-panel').hidden&&!document.hidden){if(!terrainPause&&!paused)terrainTime+=.016;drawTerrain();}terrainRaf=requestAnimationFrame(terrainTick);}terrainTick();
for(const b of document.querySelectorAll('[data-terrain]'))b.onclick=()=>{terrainMode=b.dataset.terrain;terrainData=undefined;document.querySelectorAll('[data-terrain]').forEach(v=>v.setAttribute('aria-pressed',String(v===b)));text('#terrain-mode-label',terrainMode==='cortex'?'ACTIVATION MAGNITUDE':'ABSOLUTE CANDLE RETURN');drawTerrain();};
$('#terrain-pause').onclick=()=>{terrainPause=!terrainPause;$('#terrain-pause').setAttribute('aria-pressed',String(terrainPause));text('#terrain-pause',terrainPause?'Resume scan':'Pause scan');};$('#terrain-pause').setAttribute('aria-pressed',String(terrainPause));if(terrainPause)text('#terrain-pause','Resume scan');$('#terrain-reset').onclick=()=>{terrainYaw=-.3;terrainTilt=.6;terrainZoom=1;drawTerrain();};terrainCanvas.onpointerdown=e=>{terrainPointer={x:e.clientX,y:e.clientY};terrainCanvas.setPointerCapture(e.pointerId);};terrainCanvas.onpointermove=e=>{if(!terrainPointer)return;terrainYaw+=(e.clientX-terrainPointer.x)*.006;terrainTilt=Math.max(.2,Math.min(1,(terrainTilt+(e.clientY-terrainPointer.y)*.003)));terrainPointer={x:e.clientX,y:e.clientY};drawTerrain();};terrainCanvas.onpointerup=terrainCanvas.onpointercancel=()=>terrainPointer=null;terrainCanvas.addEventListener('wheel',e=>{e.preventDefault();terrainZoom=Math.max(.6,Math.min(1.6,terrainZoom*Math.exp(-e.deltaY*.001)));drawTerrain();},{passive:false});window.addEventListener('pagehide',()=>{cancelAnimationFrame(terrainRaf);terrainResize.disconnect();});

// Scientific-drawing ornament. Equations describe existing calculations, not extra models.
function drawScientificPlate(c,cx,cy,r,time,w,h){c.save();c.lineWidth=.45;c.strokeStyle='#c7b4ca';
 for(let i=0;i<9;i++){const angle=i*Math.PI/9+time*.025;c.globalAlpha=.10;c.beginPath();c.ellipse(cx,cy,r*1.45,r*(.18+i*.055),angle,0,Math.PI*2);c.stroke();}
 for(let i=0;i<4;i++){c.globalAlpha=.12;c.setLineDash(i%2?[2,9]:[]);c.beginPath();c.arc(cx,cy,r*(1.55+i*.17),.2+i*.3,Math.PI*1.4+i*.2);c.stroke();}c.setLineDash([]);
 const sx=cx,sy=h-45,sr=28;c.globalAlpha=.22;for(let i=-3;i<=3;i++){const q=i/4;c.beginPath();c.ellipse(sx,sy+q*sr,sr*Math.sqrt(1-q*q),sr*.18*Math.sqrt(1-q*q),0,0,Math.PI*2);c.stroke();}for(let i=0;i<6;i++){c.beginPath();c.ellipse(sx,sy,sr*Math.abs(Math.cos(i*Math.PI/6+time*.08)),sr,0,0,Math.PI*2);c.stroke();}
 const equations=['rₜ = ln(Pₜ / Pₜ₋₁)','hₜ₊₁ = tanh(Wx + Ahₜ)','σ² = Σ(rₜ − μ)² / (n − 1)','Dₜ = Pₜ / max(P₀…Pₜ) − 1'];c.font='italic 10px Georgia';c.fillStyle='#c8a2bd';equations.forEach((line,i)=>{c.globalAlpha=.23;c.fillText(line,i%2?w*.62:22,40+i*(h-100)/4);});
 c.strokeStyle='#d4a3c5';c.globalAlpha=.2;for(let i=0;i<48;i++){const a=i/48*Math.PI*2,outer=r*1.58,inner=outer-(i%4===0?8:3);c.beginPath();c.moveTo(cx+Math.cos(a)*inner,cy+Math.sin(a)*inner);c.lineTo(cx+Math.cos(a)*outer,cy+Math.sin(a)*outer);c.stroke();}c.restore();}
