import {mountCortex} from './cortex-lab.js';
let disposeCortex=null;
import {assessToken} from './token-assessment.mjs';
let root=null,api=null,current=null,busy=false,generation=0;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const number=n=>Number.isFinite(n)?n.toLocaleString('en-US',{maximumFractionDigits:2}):'—';
const usd=n=>Number.isFinite(n)?new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumSignificantDigits:6}).format(n):'—';
export function unmountTokenView(){disposeCortex?.();disposeCortex=null;root=null;generation++;busy=false;}
export function mountTokenView(container,access){
 api=access;if(root?.isConnected){if(current&&!busy)paint();return;}
 root=container;root.innerHTML=`<section class="tv"><header class="tv-heading"><div><span class="tv-kicker">BRAIN CAT / RESEARCH TERMINAL</span><h2>Curiosity, with evidence<span>.</span></h2><p>One contract. A clearer picture.</p></div><div class="tv-index">01 <span>/ TOKEN VIEW</span></div></header><div id="cortex-host"></div><div class="tv-layout"><section class="tv-main"><form class="tv-search"><label for="tv-address">START WITH A CONTRACT</label><div><input id="tv-address" autocomplete="off" spellcheck="false" placeholder="Paste token address · 0x…" pattern="0x[a-fA-F0-9]{40}" required><button type="submit">Analyze ↗</button></div><span id="tv-hint">Read-only research. No wallet connection.</span></form><div class="tv-chips" id="tv-chips"></div><div class="tv-token"><div><span class="tv-kicker">SELECTED SPECIMEN</span><h3 id="tv-name">Nothing under the lens. Yet.</h3><small id="tv-contract">Choose an observed token or paste a contract above.</small></div><span id="tv-state" class="tv-pill">AWAITING INPUT</span></div><div class="tv-metrics" id="tv-metrics"></div><section class="tv-evidence"><header><h3>Evidence board</h3><span id="tv-time">NO INVESTIGATION YET</span></header><div id="tv-checks"></div><footer>Verification ≠ safety. Listed holders can include pools and contracts.</footer></section><details class="tv-source"><summary>Source notes & limitations ↗</summary><div id="tv-lines">Run an investigation to see provider findings.</div></details></section><aside class="tv-cat-panel"><header><span>FELIS / OBSERVER 01</span><button id="tv-motion" type="button" aria-pressed="false">Pause motion</button></header><div class="tv-portrait"><img src="/token-cat.png" alt="A curious monochrome cat made of fine neural threads"><svg viewBox="0 0 400 330" aria-hidden="true"><g>${[[30,100,120,60],[120,60,205,100],[205,100,290,50],[290,50,370,140],[30,100,80,220],[80,220,205,100],[205,100,310,250],[310,250,370,140]].map(([a,b,c,d])=>`<path d="M${a} ${b} L${c} ${d}"/>`).join('')}${[[30,100],[120,60],[205,100],[290,50],[370,140],[80,220],[310,250]].map(([x,y])=>`<circle cx="${x}" cy="${y}" r="3"/>`).join('')}</g></svg><div class="tv-scan"></div><span class="tv-portrait-label">ARTISTIC SIGNAL MAP</span></div><section class="tv-thought"><span class="tv-kicker">WHAT THE CAT NOTICED</span><h3 id="tv-verdict">Let’s take a closer look.</h3><p id="tv-comment">Bring me a contract. I’ll separate what we know from what still needs checking.</p><div id="tv-reasons"></div></section><footer><i></i> RULES-BASED COMMENTARY · NO PRICE PREDICTION</footer></aside></div><footer class="tv-footer"><span>OBSERVE → VERIFY → UNDERSTAND</span><span>YOUR DATA. YOUR JUDGMENT.</span></footer></section>`;
 disposeCortex=mountCortex(root.querySelector('#cortex-host'));
 root.querySelector('form').onsubmit=e=>{e.preventDefault();investigate(root.querySelector('input').value.trim());};
 root.querySelector('#tv-motion').onclick=e=>{const paused=root.querySelector('.tv').classList.toggle('tv-paused');e.target.textContent=paused?'Resume motion':'Pause motion';e.target.setAttribute('aria-pressed',String(paused));};
 const tokens=api.snapshot().tokens.slice(0,4);root.querySelector('#tv-chips').innerHTML=tokens.map(t=>`<button type="button" data-tv-address="${esc(t.address)}">${esc(t.symbol)} <span>↗</span></button>`).join('')||'<small>No observed tokens yet. Configure the data connection in Settings.</small>';
 root.querySelectorAll('[data-tv-address]').forEach(b=>b.onclick=()=>{root.querySelector('input').value=b.dataset.tvAddress;investigate(b.dataset.tvAddress);});
 if(current){root.querySelector('input').value=current.address;paint();}else paintEmpty();
}
function metric(label,value,sub){return `<article><span>${label}</span><b>${value}</b><small>${sub}</small></article>`;}
function paintEmpty(){root.querySelector('#tv-metrics').innerHTML=['PRICE','24H CHANGE','LIQUIDITY','HOLDERS'].map(n=>metric(n,'—','Awaiting evidence')).join('');root.querySelector('#tv-checks').innerHTML=['Source verification','Listed holder share','Creator','Mint / tax / blacklist / LP lock'].map(n=>`<div><span>${n}</span><b>UNKNOWN</b></div>`).join('');}
async function investigate(address){if(busy||!/^0x[a-fA-F0-9]{40}$/.test(address))return;busy=true;const id=++generation;root.querySelector('.tv').classList.add('tv-working');root.querySelector('button[type=submit]').disabled=true;root.querySelector('#tv-hint').textContent='Requesting contract evidence and available market observations…';try{const d=await api.investigate(address);if(!root||id!==generation)return;if(!d)throw Error('Investigation unavailable. Check the data connection in Settings.');current={address:address.toLowerCase(),dossier:d};paint();root.querySelector('#tv-hint').textContent='Investigation complete. Unknown checks are left unknown.';}catch(e){if(root&&id===generation)root.querySelector('#tv-hint').textContent=e.message;}finally{if(root&&id===generation){busy=false;root.querySelector('.tv').classList.remove('tv-working');root.querySelector('button[type=submit]').disabled=false;}}}
function paint(){if(!root||!current)return;const s=api.snapshot(),t=s.tokens.find(t=>t.address.toLowerCase()===current.address),d=current.dossier,c=d.checks||{},a=assessToken(t,d,Date.now(),s.demo),m=a.fresh?t?.market:null;
 root.querySelector('#tv-name').textContent=t?.symbol&&t.symbol!=='?'?`${t.symbol} / ${t.name}`:d.name||'Unresolved token';root.querySelector('#tv-contract').textContent=current.address;root.querySelector('#tv-state').textContent=s.demo?'DEMO DATA':a.fresh?'FRESH MARKET':'MARKET UNKNOWN / STALE';
 root.querySelector('#tv-metrics').innerHTML=metric('PRICE',usd(m?.price),'Provider observation')+metric('24H CHANGE',a.change===null?'—':number(a.change)+'%','Historical, not forecast')+metric('LIQUIDITY',usd(m?.liquidity),'Reported pool liquidity')+metric('HOLDERS',number(c.holders),'Provider-listed count');
 const rows=[['Source verification',c.verified===true?'VERIFIED':c.verified===false?'NOT VERIFIED':'UNKNOWN'],['Top listed holder share',Number.isFinite(c.listedShare)?number(c.listedShare)+'% · '+c.listedCount+' addresses':'UNKNOWN'],['Creator',d.creator||t?.creator||'UNKNOWN'],['Mint / tax / blacklist / LP lock','NOT CHECKED']];root.querySelector('#tv-checks').innerHTML=rows.map(([k,v])=>`<div><span>${k}</span><b>${esc(v)}</b></div>`).join('');root.querySelector('#tv-time').textContent='CHECKED '+new Date(d.checkedAt).toLocaleTimeString('en-GB');root.querySelector('#tv-verdict').textContent=a.label;root.querySelector('#tv-comment').textContent=a.summary;root.querySelector('#tv-reasons').innerHTML=a.notes.map(n=>`<p>↳ ${esc(n)}</p>`).join('');root.querySelector('#tv-lines').innerHTML=(d.lines||[]).map(n=>`<p>${esc(n)}</p>`).join('');
}
